name: AutoBuild

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm install

      # 添加构建前的目录检查
      - name: Check directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Electron directory:"
          ls -la electron/ || echo "No electron directory"

      - name: Build Electron App for windows
        if: matrix.os == 'windows-latest'
        run: pnpm run build:win

      - name: Build Electron App for macos
        if: matrix.os == 'macos-latest'
        run: |
          pnpm run build:mac
          pnpm run build:mac-arm

      # 添加构建后文件检查
      - name: Check built files
        run: |
          echo "Built files in dist-electron directory:"
          ls -la dist-electron/ || echo "No dist-electron directory"

      # 修改清理步骤 - 更保守的清理策略
      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "Files before cleanup:"
          ls -la dist-electron/
          # 只清理不需要的文件，保留所有构建产物
          pnpm exec del-cli "dist-electron/**/*.js" "dist-electron/**/*.map" "!dist-electron/*.exe" "!dist-electron/*.yml" "!dist-electron/*.blockmap" "!dist-electron/*.zip" || echo "Cleanup completed"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "Files before cleanup:"
          ls -la dist-electron/
          pnpm exec del-cli "dist-electron/**/*.js" "dist-electron/**/*.map" "!dist-electron/*.dmg" "!dist-electron/*.yml" "!dist-electron/*.zip" "!dist-electron/*.tar.gz" || echo "Cleanup completed"

      # 添加最终文件检查
      - name: Verify final artifacts
        run: |
          echo "Final artifacts:"
          ls -la dist-electron/ || echo "No dist directory"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: dist-electron/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist-electron/**/*.exe
            dist-electron/**/*.dmg
            dist-electron/**/*.yml
            dist-electron/**/*.zip
            dist-electron/**/*.blockmap
          draft: false
          prerelease: false
        env:
          GH_TOKEN: ${{ secrets.ELECTRON_TOKEN }}
